/**
 * @file main.c
 * @brief Entry point for the large EXE. Embeds a large binary blob to produce
 *        a Windows executable that is at least 120 MB in size.
 *
 * The embedded data is linked in via bigdata.o, which is generated by
 * objcopy from bigdata.bin. The symbols _binary_bigdata_bin_start and
 * _binary_bigdata_bin_end are injected automatically by objcopy.
 */

#include <stdio.h>
#include <stddef.h>

/* Symbols provided by the binary object generated from bigdata.bin */
extern const char _binary_bigdata_bin_start[];
extern const char _binary_bigdata_bin_end[];

int main(void)
{
    ptrdiff_t size = _binary_bigdata_bin_end - _binary_bigdata_bin_start;
    printf("Embedded data size: %td bytes (%.2f MB)\n",
           size, (double)size / (1024.0 * 1024.0));
    return 0;
}
